amcl:
  ros__parameters:
    use_sim_time: false
    base_frame_id: base_link
    odom_frame_id: odom
    global_frame_id: map
    scan_topic: scan
    robot_model_type: "nav2_amcl::DifferentialMotionModel"

    laser_model_type: likelihood_field
    sigma_hit: 0.2
    z_hit: 0.6
    z_rand: 0.4
    max_beams: 60
    min_particles: 500
    max_particles: 2000
    resample_interval: 1
    update_min_d: 0.05
    update_min_a: 0.10
